### ISSUE TITLE
Angelegte Daten anschauen

### ISSUE THREAD

**Issue by JSquar** [wr-hamburg/MatchFinder#17]
Man kann zwar eine Vorschau für eine Auswertung anzeigen, kann aber nicht die Listen von Teilnehmern oder Themen anzeigen. Geht in die gleiche Richtung wie #9

**Comment by kilbac** [comment]
Daten lassen sich durch einen Klick auf die Liste anschauen. Evtl. besser intuitiv bedienbar machen?

**Comment by kilbac** [comment]
https://github.com/wr-hamburg/MatchFinder/commit/6d49644ec8cf4848e76865b6c7a162dfd259c25f
