### ISSUE TITLE
Zu viele Teilnehmer berücksichtigen

### ISSUE THREAD

**Issue by JSquar** [wr-hamburg/MatchFinder#2]
Wenn es mehr Teilnehmer gibt, als die Kombination aus Themenzahl und maximaler Stimmenzahl pro Thema erlaubt, wird aktuell zufällig ein Teilnehmer unterdrückt. So eine Kombination dürfte nicht möglich sein!

Mögliche Vorgehensweisen:
a) Erstellung der Verteilung nicht erlauben
b) Option anbieten, dass bei der Auswertung dann die Pechvögel mit NA-Themen versehen werden, damit man für diese Leute nochmal gezielt alternative Themen suchen kann (Warnung sollte dabei ausgegeben werden)

**Comment by TheFinestHobo** [comment]
scheint gefixed zu sein, da jetzt Strings Ints sind
