### ISSUE TITLE
Auswahl-Fenster minimaler Stimmen zu nervös

### ISSUE THREAD

**Issue by JSquar** [wr-hamburg/MatchFinder#7]
Das Auswahl-Fenster, wo man angibt, wie viele Stimmen minimal vergeben werden sollen, ist etwas nervös. Direkt-Eingaben werden ignoriert, stattdessen kommt die Fehlermeldung, dass es nicht genügend Stimmen gibt

**Comment by TheFinestHobo** [comment]
fixed and pushed to dev
